# Generated by Django 4.1.5 on 2023-01-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc',
            new_name='team_desc',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='image',
            new_name='team_image',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
    ]
