# Generated by Django 4.1.5 on 2023-01-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_alter_team_team_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
