# Generated by Django 4.1.5 on 2023-01-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='frge', upload_to='images'),
            preserve_default=False,
        ),
    ]
