# Generated by Django 4.1.5 on 2023-02-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_alter_movies_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
