# Generated by Django 4.1.5 on 2023-02-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_alter_movies_decs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
